### ISSUE TITLE
redundantne repozitare

### ISSUE THREAD

**Issue by fr6nco** [aks-2017/semestralne-zadania-semestralne-zadanie-72447-48072-1#1]
zdravim,

mate 2 repozitare. jeden s nazvom semestralne-zadania-semestralne-zadanie-72447-48072-1 a druhy semestralne-zadania-semestralne-zadanie-72447-48072. 

Ktory mozem vymazat. Prosim, poslite mi aj ais loginy (xmeno1, xmeno2). Upravim nazov repozitaru potom

**Comment by MartinBalaz** [comment]
dobry den,

semestralne-zadania-semestralne-zadanie-72447-48072-1  tam nieco bolo tak
neviem ci semestralne-zadania-semestralne-zadanie-72447-48072 nie je zle
vytvoreny. Cize ak by sa dalo tak semestralne-zadania-
semestralne-zadanie-72447-48072 vymazat a semestralne-zadania-
semestralne-zadanie-72447-48072-1 premenovat tak ze sa odstrani ta jednotka.

2017-10-24 16:32 GMT+02:00 Thomas Boros <notifications@github.com>:

**Comment by fr6nco** [comment]
este mi poslite ais loginy. premenujem repozitar..namiesto cisel dam loginy

**Comment by MartinBalaz** [comment]
xbalazm1, xvrbal
